### ISSUE TITLE
Blank page when using Share Email in Hebrew

### ISSUE THREAD

**Issue by Terrafire123** [addthis/addthis-angularjs#1]
When using Share Email in hebrew, I get a blank page. It LOOKS like the reason is because there's an improperly formatted quotation mark **"** in the sendWithDifferentServices section of **translations_table** .

![image](https://user-images.githubusercontent.com/30175427/30001663-dcb539e6-909c-11e7-86e1-ca14770a1190.png)

Sample URL: https://www.addthis.com/tellfriend_v2.php?v=300&winname=addthis&pub=atacademy&source=tbx-300&lng=en&s=email&wid=fhss&url=http%3A%2F%2Fwww.addthis.com%2Facademy%2Fadd-email-share-buttons-newsletter%2F&title=How%20To%20Add%20Email%20Share%20Buttons%20To%20Your%20Newsletter%20-%20AddThis%20Academy&ate=AT-atacademy/-/per-2/59abbee51abe3bad/2&uid=59abbc10ffcb171a&description=NOTE%20FOR%20EXISTING%20USERS%3A%20We%20recently%20made%20some%20changes%20to%20our%20tool%20gallery%2C%20and%20one%20of%20those%20changes%20included%20moving%20the%20Email%20Newsletter%20buttons%20to%20a%20purely%20code%20installation%20as%20opposed%20to%20being%20able%20to%20configure%20and%20edit%20in%20the%20dashboard.%20If%20you%20have%20buttons%20already%20in%20your%20newsletter%2C%20we%20will%20continue%20to%20support%20them.%20%E2%80%A6%20Continue%20reading%20How%20To%20Add%20Email%20Share%20Buttons%20To%20Your%20Newsletter%20%E2%86%92&uud=1&ct=1&ui_email_to=&ui_email_from=&ui_email_note=&pre=http%3A%2F%2Fwww.addthis.com%2Facademy%2F%3Fs%3Dshare%2Bemail&tt=0&captcha_provider=recaptcha2&pro=0&ats=imp_url%3D0%26smd%3Drsi%253D%2526gen%253D0%2526rsc%253D%2526dr%253Dhttp%25253A%25252F%25252Fwww.addthis.com%25252Facademy%25252F%25253Fs%25253Dshare%25252Bemail%2526sta%253DAT-atacademy%25252F-%25252F-%25252F59abbee51abe3bad%25252F1%26hideEmailSharingConfirmation%3Dundefined%26service%3Demail%26media%3Dundefined%26passthrough%3Dundefined%26email_template%3Dundefined%26email_vars%3Dundefined&atc=username%3Datacademy%26services_exclude%3D%26services_exclude_natural%3D%26services_compact%3Dfacebook%252Ctwitter%252Cprint%252Cemail%252Cpinterest_share%252Cgmail%252Cgoogle_plusone_share%252Clinkedin%252Cmailto%252Ctumblr%252Cmore%26product%3Dtbx-300%26widgetId%3Dfhss%26pubid%3Datacademy%26ui_pane%3Demail&rb=false

**Comment by icelander** [comment]
Hi there,

This looks like an issue with our email sharing service and not with the AngularJS plugin. Could you send an email with the details to help@addthis.com?

**Comment by gnurik** [comment]
not an issue with plugin
