### ISSUE TITLE
Documentation out of Date

### ISSUE THREAD

**Issue by selected-pixel-jameson** [addthis/addthis-angularjs#10]
For anyone else who stumbles across this and is wondering why nothing is working according to the documentation refer to this site. https://addthis.github.io/addthis-angularjs/#/api/addthis.$addthis

**Comment by dmvjs** [comment]
the site mentioned ^^^ is now included in the docs folder of this project

**Comment by selected-pixel-jameson** [comment]
You should update the documentation in the repository which contains the incorrect documentation as well.
