### ISSUE TITLE
Publish last version to NPM

### ISSUE THREAD

**Issue by ghost** [addthis/addthis-angularjs#13]
Hi there, I'm having some troubles using your library on production, this error appears:
`Uncaught Error: [$injector:unpr] Unknown provider: tProvider <- t <- $addthis <- $addthis`
I'm using AngularJS 1.6.9 and the building system is Webpack 3.10.0.

It looks like someone [already opened an issue about that](https://github.com/addthis/addthis-angularjs/issues/4), and it was [fixed on the last version of the package (1.0.4)](https://github.com/addthis/addthis-angularjs/releases/tag/1.0.4) though, as it hasn't been published to NPM, I can't upgrade without reinstalling the dependency as a repository.

**Comment by dbroudy** [comment]
In installed as a repository, waiting for the next release to switch back to npm. Any update on this?

**Comment by selected-pixel-jameson** [comment]
Finally getting back to looking into this and I can verify that the latest commit does fix the issue, but yes you are correct that they haven't published it to NPM since I was last on here talking about how there were issues.

**Comment by dmvjs** [comment]
Sorry, trying to publish 1.0.4 but getting `'@oracle/addthis-angularjs' is not in the npm registry.` Hopefully I can resolve this soon.

**Comment by dmvjs** [comment]
OK published, future releases should be easier.
Thanks for your patience.
