### ISSUE TITLE
this._targetWindow.postMessage is not a function.

### ISSUE THREAD

**Issue by dtaylorsam** [addthis/addthis-angularjs#3]
I'm getting error:
this._targetWindow.postMessage is not a function. (In 'this._targetWindow.postMessage(e,this._targetOrigin)', 'this._targetWindow.postMessage' is undefined)

in many Safari and mobile Safari versions: Safari 11.0.1, Mobile Safari 11.0, Safari 9.1.3, WebKit 604.1.38 (iOS 11.0.3)

I'm not sure if it's tied to this module or some other setting, but I do have another addthis angular module and pub key that is working as expected.

I've also submitted a ticket to addthis support.  #284024

![addthis-issue](https://user-images.githubusercontent.com/12175783/33666872-83d50dfa-da58-11e7-8dd9-4cfc57fa3b21.PNG)

plnkr example:
https://plnkr.co/edit/JjemqFppQqM1n6OQ0GB1?p=preview  (click the more button to open the widget)

**Comment by lelandtran77** [comment]
@dtaylorsam Just wanted to let everyone know that this is currently being worked on by our devs and is expected to be fixed in Q1!

**Comment by dmvjs** [comment]
this appears to be an issue with addthis_widget.js, not this plugin
