### ISSUE TITLE
Unable to Minifiy / Concat / Package for Production.

### ISSUE THREAD

**Issue by selected-pixel-jameson** [addthis/addthis-angularjs#4]
When I try to build this for production I get the following error.

Uncaught Error: [$injector:unpr] Unknown provider: eProvider <- e <- $addthis <- $addthis
http://errors.angularjs.org/1.5.11/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20%24addthis%20%3C-%20%24addthis
    at vendor-6ed59de381.js:31
    at vendor-6ed59de381.js:31
    at Object.n [as get] (vendor-6ed59de381.js:31)
    at vendor-6ed59de381.js:31
    at n (vendor-6ed59de381.js:31)
    at i (vendor-6ed59de381.js:31)
    at Object.o [as invoke] (vendor-6ed59de381.js:31)
    at vendor-6ed59de381.js:31
    at n (vendor-6ed59de381.js:31)
    at i (vendor-6ed59de381.js:31)
    at Object.o [as invoke] (vendor-6ed59de381.js:31)
    at vendor-6ed59de381.js:31
    at n (vendor-6ed59de381.js:31)
    at it (vendor-6ed59de381.js:31)
    at o (vendor-6ed59de381.js:31)

**Comment by dmvjs** [comment]
does the latest merge fix your issue?

**Comment by selected-pixel-jameson** [comment]
Obviously the positive response would be testing it out to see if it does resolve the issue. However, I spent hours trying to get this to work and never was able to so I really don't feel like wasting any more time on an issue that, according to the pull request that was submitted, is approximately 5 months old. If I could convey one thing it would be for AddThis to provide better documentation. And by better I mean one single place to get documentation information for all of it's libraries. The final solution I ended up with was something that I found on SO and was undocumented as far as I could tell. I understand that 90% of your traffic is probably coming from Wordpress Plugins, but if you're not going to actively support libraries or even accept PR's then maybe don't instruct users to use them on your website.

**Comment by dmvjs** [comment]
Thank you for the constructive criticism; we're trying to make this better one day at a time. I asked if it solved your issue because it does work without issue for me but I'm not sure about the setup you are using, specifically wrt how you are doing the building/minifying, which version of Angular you are using, and how exactly you are including/providing the angular & addthis scripts. We are actively working to make the improve plugins and to provide better documentation for developers.

**Comment by selected-pixel-jameson** [comment]
Finally getting back to this. I can verify that this has been fixed. Please publish this fix to NPM.

**Comment by selected-pixel-jameson** [comment]
Seems to be resolved at this point.
