### ISSUE TITLE
$addthisProvider.profile_id is not a function

### ISSUE THREAD

**Issue by selected-pixel-jameson** [addthis/addthis-angularjs#5]
Can't use profile_id when trying to set the id in the configuration.   $addthisProvider.config() works fine though.

**Comment by selected-pixel-jameson** [comment]
Also get the exact same message when trying to use $addthis.share_url()

**Comment by dmvjs** [comment]
`$addthisProvider.profile_id` this was a typo in the README, fixed in the latest release 1.0.4
